// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TUM.SimpleLinkChecker.Data;

#nullable disable

namespace TUM.SimpleLinkChecker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240529195940_AddWebRefType")]
    partial class AddWebRefType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TUM.SimpleLinkChecker.Data.Scrape", b =>
                {
                    b.Property<Guid>("ScrapeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("text");

                    b.Property<bool>("Finished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScrapeId");

                    b.ToTable("Scrapes");
                });

            modelBuilder.Entity("TUM.SimpleLinkChecker.Data.Snapshot", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("C_Description")
                        .HasColumnType("text");

                    b.Property<string>("C_Title")
                        .HasColumnType("text");

                    b.Property<string>("C_Typo3PageId")
                        .HasColumnType("text");

                    b.Property<string>("ContentExceptionMessage")
                        .HasColumnType("text");

                    b.Property<string>("ContentExceptionType")
                        .HasColumnType("text");

                    b.Property<bool?>("ContentScraped")
                        .HasColumnType("boolean");

                    b.Property<int>("ContentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<bool>("Downloaded")
                        .HasColumnType("boolean");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("text");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScrapeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SnapshotId");

                    b.HasIndex("ScrapeId");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("TUM.SimpleLinkChecker.Data.WebRef", b =>
                {
                    b.Property<Guid>("WebRefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("LinkMalformed")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkText")
                        .HasColumnType("text");

                    b.Property<string>("RawLink")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("XPath")
                        .HasColumnType("text");

                    b.HasKey("WebRefId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetId");

                    b.ToTable("WebRefs");
                });

            modelBuilder.Entity("TUM.SimpleLinkChecker.Data.Snapshot", b =>
                {
                    b.HasOne("TUM.SimpleLinkChecker.Data.Scrape", "Scrape")
                        .WithMany("Snapshots")
                        .HasForeignKey("ScrapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scrape");
                });

            modelBuilder.Entity("TUM.SimpleLinkChecker.Data.WebRef", b =>
                {
                    b.HasOne("TUM.SimpleLinkChecker.Data.Snapshot", "Source")
                        .WithMany("OutgoingLinks")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TUM.SimpleLinkChecker.Data.Snapshot", "Target")
                        .WithMany("IncomingLinks")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("TUM.SimpleLinkChecker.Data.Scrape", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("TUM.SimpleLinkChecker.Data.Snapshot", b =>
                {
                    b.Navigation("IncomingLinks");

                    b.Navigation("OutgoingLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
